sudo: required
services:
  - docker

before_install:
  - docker build -t olusolaakinsulere/docker-react -f Dockerfile.dev .


script:
  - docker run olusolaakinsulere/docker-react npm run test -- --coverage